### ISSUE TITLE
So much friction!

### ISSUE THREAD

**Issue by jeffrafter** [jeffrafter/emo#3]
Shut up! @pmarsceill SHUT UP @jeffrafter

😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 

🔪 🐰 
🔪 🐰 
🔪 🐰 
🔪 🐰 
🔪 🐰 
🔪 🐰

**Comment by jeffrafter** [comment]
Test

**Comment by pmarsceill** [comment]
Yo

**Comment by pmarsceill** [comment]
Shut. Up.
